baseURL = "https://www.tinysociety.co/"
DefaultContentLanguage = "en"
title = "Tiny House Society"
theme = "tinysociety"
description = ""

# Pointing to this file
config = "config.toml"
contentdir = "content"
# Create an array of files you don't want hugo to build
ignoreFiles = []
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = ""
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.tinysociety.co/"
  siteaddressno = "https://www.tinysociety.co"
  ## FB share info
  fbpagename = "tinyhouseloversofficial"
  fbappid = "236775637052135"
  ## Business name in Schema.org
  schemabiz = "Tiny House Society"
  ## Google Tag Manager tracking ID
  gtmid = "GTM-M53C3ZX"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[permalinks]
  singles = "/:slug/"

[taxonomies]
  category = "categories"
  collection = "collections"

# [Languages.fr]
# [Languages.fr.Taxonomies]
# category = "categories"
# createur = "createurs"
