backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: master # Branch to update (master by default)
  squash_merges: true

media_folder: "themes/tinysociety/source-images" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow

collections:
### ARTICLES
  - name: "articles" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "en"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Slug/Link (if link is https://www.tinysociety.co/articles/tiny-house-roof, value is tiny-house-roof)", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
      - label: "Author" 
        name: "author"
        widget: "select"
        options:
          - { label: "David Morneau", value: "davidm" }
          - { label: "Rose Burke", value: "kristen" }
          - { label: "Molli McGee", value: "molli" }
          - { label: "Alexis Grenon", value: "alexis" }
          - { label: "Guest Post", value: "guest" }
      - {label: "Banner and share image (rectangle - 2700px by 1800px)", name: "image", widget: "image" , required: false}
      - {label: "Add a black overlay?", name: "overlay", widget: "boolean", required: false, default: true}
      - {label: "Publication date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Update date", name: "lastmod", widget: "datetime", format: "YYYY-MM-DD"}
      - name: notloaded
        label: "Loading effect"
        widget: object
        fields:
          - {label: "Do you need it?", name: "need", widget: "boolean", required: false, default: true}
      - name: listing
        label: "Home page and articles page"
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Summary", name: "description", widget: "text"}
          - {label: "Square Image (square - 800px by 800px)", name: "image", widget: "image", required: false}
      - label: "Categories" 
        name: "categories"
        widget: "select"
        multiple: true
        options: [ "Architecture and design", "DIY", "Energy efficiency", "Sustainable building and living", "Tiny cabins", "Tiny house review", "Tiny houses", "Tiny lifestyle", "Tiny house financing" ]
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}
      - {label: "Menu ID", name: "menuid", widget: "hidden", default: "articles"}
      - {label: "Priority (0 is the most important)", name: "ordre", widget: "number", default: 0, required: false}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Infographic?", name: "infographic", widget: "boolean", required: false, default: false}
      - {label: "Hide from website?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Remove from search engine?", name: "noindex", widget: "boolean", required: false, default: false}
      - {label: "H3 included", name: "hincluded", widget: "hidden", default: false}
      - {label: "Special map", name: "mapsjs", widget: "hidden", default: false}
### PLANS
  - name: "plans" # Used in routes, e.g. /admin/collections/blog
    label: "Plans" # Used in the UI
    folder: "content/plans" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "tosale"
      value: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Slug/Link (if link is https://www.tinysociety.co/plans/tiny-house-roof, value is tiny-house-roof)", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"]}
      - label: "Architect" 
        name: "architect"
        widget: "select"
        options:
          - { label: "Hesham Younis", value: "hesham" }
          - { label: "Anastasia", value: "anastasia" }
      - {label: "Share image (ideally rectangle - 1200px x 630px)", name: "image", widget: "image" , required: false}
      - {label: "Publication date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - name: listing
        label: "Shop page information"
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Main Image (rectangle - 1080px by 720px)", name: "image", widget: "image", required: false}
          - {label: "On foundation?", name: "foundation", widget: "boolean", required: false, default: false}
      - {label: "Name of the plan", name: "titre", widget: "string"}
      - name: slider
        label: "Images for slider (rectangle - 2000px x 1200px"
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image (rectangle - 2000px by 1200px)", name: "image", widget: "image", required: false}
      - {label: "Rating", name: "rating", widget: "string"}
      - {label: "Collections (separate with commas)", name: "collections", widget: "list"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}
      - {label: "To Sale", name: "tosale", widget: "hidden", default: true}
      - {label: "Menu ID", name: "menuid", widget: "hidden", default: "plans"}
      - {label: "Priority (0 is the most important)", name: "ordre", widget: "number", default: 0, required: false}
      - {label: "Hide from website?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Remove from search engine?", name: "noindex", widget: "boolean", required: false, default: false}
      - name: section1
        label: "Key Features"
        widget: object
        fields:
          - {label: "Area", name: "area", widget: "string"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Nb of floor", name: "floor", widget: "string"}
      - {label: "Plan description", name: "section2", widget: "markdown", required: false}
      - name: section3
        label: "Floor plans"
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Floor Image", name: "image", widget: "image", required: false}
      - name: section4
        label: "Full specs & features"
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - name: col1
            label: "Middle Column"
            widget: list
            fields:
              - {label: "Name", name: "title", widget: "string"}
          - name: col2
            label: "Last Column"
            widget: list
            fields:
              - {label: "Name", name: "title", widget: "string"}
### CTA
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "cta"
        label: "CTA"
        file: "data/cta.yml"
        description: "Call to action"
        fields:
          - name: typeform
            label: List of CTAs
            widget: list
            allow_add: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Identifier"
                name: "slug"
                pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Please use format: ceci-est-unique"]
                widget: "relation"
                collection: "articles"
                searchFields: ["slug","title"]
                valueField: "slug"
                displayFields: ["title", "slug"]
                hint: "Find the page on which you want to see this CTA by typing it's slug, or it's title. There should be autosuggestions to help you."
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button text", name: "btn", widget: "string"}
              - {label: "Typeform Code", name: "typeformid", widget: "string", hint: "Have a look at other examples to understand what this is. It is a short code that identifies your typeform. It should look like: UynMh4"}